### ISSUE TITLE
Selecting more than "25 menu items from categories" doesn't show any orders

### ISSUE THREAD

**Issue by GrantBartlett** [ryanmitchell/ti-ext-kitchendisplay#27]
**Steps to reproduce:**

- Select > 25 categories in the "Show menu items from categories" dropdown
- Click save (It will automatically change the dropdown to all) 
- Orders no longer appear in the View.

![image](https://user-images.githubusercontent.com/6104940/100523075-6ba0d780-31a5-11eb-9522-5c4a6796bc65.png)

**Comment by ryanmitchell** [comment]
I suspect your hitting the maximum field length in the database which is then causing issues... are you able to modify the database field type? If so modify "categories" in ti_thoughtco_kitchendisplay to be a TINYTEXT instead of VARCHAR 128 and resave to see if it helps? If so I'll add it to the next update.

**Comment by BreakSecurity** [comment]
I have the same

**Comment by BreakSecurity** [comment]
@ryanmitchell TINYTEXT solve the problem!

**Comment by ryanmitchell** [comment]
Fixed
